### ISSUE TITLE
Provide a docker image for S3Proxy so users can run it anywhere

### ISSUE THREAD

**Issue by ritazh** [andrewgaul/s3proxy#103]
I have implemented something [here](https://github.com/ritazh/s3proxydocker). I'm open to suggestions and feedback to make it better. Would be great if we could add a reference of it to the README of S3Proxy as another option to run S3Proxy.

**Comment by andrewgaul** [comment]
s3proxydocker is a great idea and insulates people from the vagaries of Java.  I look forward to seeing how people use it!
