### ISSUE TITLE
encoding-type not supported

### ISSUE THREAD

**Issue by dleute** [andrewgaul/s3proxy#104]
Newer versions of the aws cli are including an encoding-type url parameter. I solved this temporarily by backing off to awscli version 1.9.9 using pip. Anything later than that creates issues with s3proxy.

s3proxy throws this:

```A server error (NotImplemented) occurred when calling the ListObjects operation: A header you provided implies functionality that is not implemented.```

Obviously I could add it to the supported parameters list to make the problem go away. But probably not the best option if it's supposed to actually accomplish something.

**Comment by andrewgaul** [comment]
Interesting, the `url` parameter allows some additional characters in the range 0x00 to 0x1F which were previously not allowed.  Could you add some tests and implement functionality to URL encode blob names when this parameter is present?  I found this reference helpful:

https://github.com/aws/aws-sdk-java/issues/333

**Comment by dleute** [comment]
Just to sum up: Any time s3proxy is writing to an xml file, the blobNames written should be urlencoded if the content-type url parameter is 1. Present and 2. set to url.

Blobnames are written to XML in one of the multipart upload functions and in the listParts function.

I think I can fix the code. Not sure I can get tests written. Let me fix it first.

**Comment by dleute** [comment]
I wonder if this applies to container names to.
