### ISSUE TITLE
Forbidden InvalidAccessKeyId errors with 1.4.0

### ISSUE THREAD

**Issue by andrew311** [andrewgaul/s3proxy#105]
I have a simple s3proxy setup I'm using for testing. On upgrading from 1.3.0 to 1.4.0, now I'm getting Forbidden InvalidAccessKeyId when I try to create a bucket via boto using s3 connection.

I can't find anything that solves this in the wiki, source, or documentation of s3proxy or jcloud. Can someone tell me what I'm doing wrong? 

Here is my s3proxy config:

```
s3proxy.authorization=none
s3proxy.endpoint=http://0.0.0.0:9999
jclouds.provider=filesystem
jclouds.identity=identity
jclouds.credential=credential
jclouds.filesystem.basedir=/app/files
```

Here is the code I'm using to create buckets:

``` python
from boto.s3.connection import S3Connection, OrdinaryCallingFormat

if __name__ == '__main__':
    conn = S3Connection(aws_access_key_id='identity', aws_secret_access_key='credential',
                        calling_format=OrdinaryCallingFormat(),
                        is_secure=False, host='localhost', port=9999)

    conn.create_bucket('test')
    print conn.get_all_buckets()
```

And here is the error:

```
$ python create_buckets.py
Traceback (most recent call last):
  File "create_buckets.py", line 8, in <module>
    conn.create_bucket('test')
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" ?><Error><Code>InvalidAccessKeyId</Code><Message>Forbidden</Message><RequestId>4442587FB7D0A2F9</RequestId></Error>
```

**Comment by andrewgaul** [comment]
You have configured S3Proxy for anonymous access but Boto is providing an identity and credential.  S3Proxy incorrectly checks the credentials in this case and I fixed this in master via 618c35054c050ae2d92e9632e7987485de132096.  You can work around this in the mean-time by configuring S3Proxy with:

```
s3proxy.authorization=aws-v2
s3proxy.identity=identity
s3proxy.credential=credential
```

or configuring Boto:

```python
conn = S3Connection(calling_format=OrdinaryCallingFormat(),
                    is_secure=False, host='localhost', port=9999)
```

**Comment by andrew311** [comment]
@andrewgaul Thanks for the workaround! I will give it a shot and report back.

**Comment by andrewgaul** [comment]
1.5.0 released with fix.
