### ISSUE TITLE
ListBucketResult differs from AWS S3

### ISSUE THREAD

**Issue by RobbKistler** [andrewgaul/s3proxy#119]
s3proxy 1.4.0 (06ec55e4df9ca7677ea6c8cc45bf90df97004969)

config file:
```
s3proxy.endpoint=http://127.0.0.1:8080
s3proxy.authorization=aws-v2
s3proxy.identity=local-identity
s3proxy.credential=local-credential

jclouds.provider=transient
jclouds.identity=remote-identity
jclouds.credential=remote-credential
```
Create a bucket:
```curl -X PUT "http://s3host/somebucket"```

Create an object named "dir/"
```curl -X PUT "http://s3host/somebucket/dir/" -H "Content-Length: 0"```

List the bucket with these query parameters:
```curl "http://s3host/somebucket?delimiter=/&max-keys=1000&prefix=dir/"```

The result from AWS contains one key
```
  <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
...
    <Contents>
      <Key>dir/</Key>
...
    </Contents>
  </ListBucketResult>
```

The result from S3Proxy contains no keys:
```
  <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  </ListBucketResult>
```

Create a second object:
```curl -X PUT "http://s3host/somebucket/dir/file" -H "Content-Length: 0"```

The result from AWS contains two keys.
```
  <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
...
    <Contents>
      <Key>dir/</Key>
...
      <Key>dir/file</Key>
...
    </Contents>
  </ListBucketResult>
```

The result from S3Proxy contain two keys, in a different order.
```
  <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
...
    <Contents>
      <Key>dir/file</Key>
...
      <Key>dir/</Key>
...
    </Contents>
  </ListBucketResult>
```

The  [Amazon S3 spec is explicit about the AWS implementation returning keys alphabetically](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html)

**Comment by andrewgaul** [comment]
Could you retest with master?  jclouds 2.0.0 has improvements to both prefixes and delimiters.  I see the following:

```xml
$ curl -X PUT "http://127.0.0.1:8081/somebucket"

$ curl -X PUT "http://127.0.0.1:8081/somebucket/dir/" -H "Content-Length: 0"

$ curl "http://127.0.0.1:8081/somebucket?delimiter=/&prefix=dir/"
<?xml version="1.0" ?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
...
<Contents>
  <Key>dir/</Key>
  ...
</Contents>
</ListBucketResult>  

$ curl -X PUT "http://127.0.0.1:8081/somebucket/dir/file" -H "Content-Length: 0"

$ curl "http://127.0.0.1:8081/somebucket?delimiter=/&prefix=dir/"
<?xml version="1.0" ?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
...
<Contents> 
  <Key>dir/</Key>
  ...
</Contents>
<Contents>
  <Key>dir/file</Key>
  ...
</Contents>
</ListBucketResult>
```

**Comment by RobbKistler** [comment]
I retested with master.  The results do match AWS S3.  

Thanks!    (I didn't realize how easy it would be to build)
