### ISSUE TITLE
Provide mechanism to ignore unknown headers instead of issuing unsupported error

### ISSUE THREAD

**Issue by rchs986** [andrewgaul/s3proxy#130]
I'd like to use s3proxy as a test environment for a client that will eventually work against S3. This client includes the "x-amz-server-side-encryption" header which currently results in an exception (with s3proxy):

`com.amazonaws.services.s3.model.AmazonS3Exception: A header you provided implies functionality that is not implemented.`

I could of course configure my client to not send the header depending on what backend it's working with at the time, however I'd rather that be transparent to the client. And given this is for testing purposes I'm OK with the data not actually being encrypted.

**Comment by andrewgaul** [comment]
You can now configure this via setting `s3proxy.ignore-unknown-headers` to true.  Longer-term I would like to add support for object encryption to S3Proxy but the underlying jclouds library does not support this feature.  Unfortunately it looks difficult to support cross-provider so it will likely take some time.

**Comment by rchs986** [comment]
Thanks Andrew. That's awesome.

**Comment by ptimsonbbc** [comment]
@andrewgaul Did this make it to 1.4.0 it is it part of 1.5.0?

**Comment by andrewgaul** [comment]
@ptimsonbbc This is fixed only in 1.5.0.

**Comment by ptimsonbbc** [comment]
@andrewgaul Thanks, when will this be made available via Maven?

**Comment by andrewgaul** [comment]
Unfortunately the Apache jclouds 2.0.0 release blocks S3Proxy 1.5.0.  In the mean-time you can use 1.5.0-SNAPSHOT via the Sonatype snapshot repository:

http://stackoverflow.com/a/7717234
