### ISSUE TITLE
Provide ability to also ignore unknown parameters

### ISSUE THREAD

**Issue by historus** [andrewgaul/s3proxy#138]
There is already an option to ignore unknown headers.
It would be helpful to also ignore unknown parameters.

**Comment by andrewgaul** [comment]
Which parameter does S3Proxy not support?

**Comment by robbypond** [comment]
encoding-type

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ListObjectsRequest.html#withEncodingType-java.lang.String-

**Comment by andrewgaul** [comment]
@robbypond Can you test with 1.5.0 pre-release?  d8c73bc86d30e885e743eb7afcd41cf0b9e9497b added support for `encoding-type`.

**Comment by robbypond** [comment]
Yes that works, I commented before I looked at that tagged build. When are you planning to release 1.5.0?

**Comment by andrewgaul** [comment]
S3Proxy 1.5.0 release is blocked on Apache jclouds 2.0.0.  Not sure when they will release it though.

**Comment by historus** [comment]
Sorry for use late response, busy times. I've seen x-amz-... parameters which led to the unknown parameter failure.

**Comment by andrewgaul** [comment]
@historus Can you be more specific?

**Comment by andrewgaul** [comment]
Closed after months of lack of response.

**Comment by historus** [comment]
E 10-18 13:06:32.338 S3Proxy-24 o.gaul.s3proxy.S3ProxyHandler:480 |::] Unknown parameters X-Amz-Expires with URI /temporary-bucket/68ae4a90-f079-02d1-6b06-fa3cd4e3aa26/c697097d-aad2-4d8c-293c-a4159f0a9286

**Comment by smigfu** [comment]
Can we reopen this? For instance generating presigned URLs do allow for additional parameters (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.html#addRequestParameter-java.lang.String-java.lang.String-).

If I add my custom parameters s3proxy will report an error:

```
E 02-20 16:01:46.936 S3Proxy-23 o.gaul.s3proxy.S3ProxyHandler:456 |::] Unknown parameters XYZ with URI ABC
```

**Comment by smigfu** [comment]
I could provide a fix for this as well, if we agree on this being an issue =)

**Comment by smigfu** [comment]
Here is a scenario in which s3proxy needs to support unknown parameters:

- create a presigned URL and add custom request-parameters to it (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.html#addRequestParameter-java.lang.String-java.lang.String-)
- the client will use the generated presigned url to upload/download content
- this work with S3 but s3proxy is throwing an error

We use this approach to add additional informations to the presigned URLs which will be evaluated in a 2nd step.

I have create a PR for this issue (similar to the support for unknown headers): https://github.com/andrewgaul/s3proxy/pull/186
