### ISSUE TITLE
Java List Buckets Client Error

### ISSUE THREAD

**Issue by ptimsonbbc** [andrewgaul/s3proxy#149]
Hello,

I seem to be getting a client error with 1.5.0 when trying to list buckets

**Code**

```
String endpoint = "http://127.0.0.1:8085";
URI uri = URI.create(endpoint);
Properties properties = new Properties();
properties.setProperty("s3proxy.authorization", "none");
properties.setProperty("s3proxy.endpoint", endpoint);
properties.setProperty("jclouds.provider", "filesystem");
properties.setProperty("jclouds.filesystem.basedir", "/tmp/s3proxy");

ContextBuilder builder = ContextBuilder
        .newBuilder("filesystem")
        .credentials("x", "x")
        .modules(ImmutableList.<Module>of(new SLF4JLoggingModule()))
        .overrides(properties);
BlobStoreContext context = builder.build(BlobStoreContext.class);
BlobStore blobStore = context.getBlobStore();

S3Proxy s3Proxy = S3Proxy.builder().awsAuthentication("x", "x").endpoint(uri).keyStore("", "").blobStore(blobStore).build();
s3Proxy.start();

BasicAWSCredentials awsCredentials = new BasicAWSCredentials("x", "x");

AmazonS3Client client = new AmazonS3Client(awsCredentials, new ClientConfiguration());
client.setEndpoint(endpoint);

// List Buckets
List<Bucket> buckets = client.listBuckets();
**
```

**Exception**
```
com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 4442587FB7D0A2F9)
, S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1386)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:939)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:465)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4031)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3968)
	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:871)
	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:877)
        ...
```

**Comment by ptimsonbbc** [comment]
Sorry this happens with all request so obviously I'm doing something wrong!

**Comment by ptimsonbbc** [comment]
Semed to be missing the S3SignerType, is this expected?

`AmazonS3Client client = new AmazonS3Client(awsCredentials, new ClientConfiguration().withSignerOverride("S3SignerType"));
`

**Comment by andrewgaul** [comment]
@ptimsonbbc Overriding `S3SignerType` opts into V2 signatures.  If your calls work with this but not without it, that means that V4 signatures are broken.  Perhaps your region is different than the emulated us-east-1 region that S3Proxy uses?

**Comment by ptimsonbbc** [comment]
@andrewgaul I can confirm that client is set as us-east-1 but I still get 400 error.

**Comment by andrewgaul** [comment]
@ptimsonbbc Sorry I cannot reproduce your symptoms.  Could you modify `S3AwsSdkTest` to match your application's behavior and submit a pull request with the failing additions?  Note that the tests in this class use V4 by default.

**Comment by ptimsonbbc** [comment]
@andrewgaul So after upgrading to 1.5.0-SNAPSHOT everything is working :) 👍 Thanks for all your help. Will just have to wait for JClouds 2.0.0 now!

**Comment by andrewgaul** [comment]
Sorry I forgot that 1.5.0 added V4 support.  The lack of a more current release frustrates users and I am working with the jclouds team to get a new version out this month.  Unfortunately it is a big project and moves slowly.

**Comment by ptimsonbbc** [comment]
No worries, sounds frustrating for you as it's blocking this project now!
