### ISSUE TITLE
How do I override LOG_LEVEL when running main file

### ISSUE THREAD

**Issue by kishore25kumar** [andrewgaul/s3proxy#153]
I want to override log level to INFO. By default all the DEBUG and above message are printed in my log. How do I override log level?

**Comment by andrewgaul** [comment]
I am not sure I understand how you are invoking S3Proxy.  If you are running the jar, you can set the log level via system properties:

```
java -DLOG_LEVEL=info s3proxy.jar --properties s3proxy.conf
```

**Comment by kishore25kumar** [comment]
I am running main.java in intellij IDE. I have set -DLOG_LEVEL but still all the debug messages are printing.

**Comment by andrewgaul** [comment]
Sorry I cannot help with your IDE.  logback consumes the system property LOG_LEVEL so I would look into that.

**Comment by andrewgaul** [comment]
Marking as resolved.
