### ISSUE TITLE
S3proxy via SSL

### ISSUE THREAD

**Issue by Andrey198** [andrewgaul/s3proxy#159]
Good day to all.

Trying to run s3proxy with SSL on Windows, 
_java -jar s3proxy --properties s3proxy.conf_

have a conf:

_s3proxy.authorization=none
s3proxy.secure-endpoint=https://127.0.0.1:8443
s3proxy.keystore-path=requestprivkey.pfx
s3proxy.keystore-password=Password8
s3proxy.endpoint=http://127.0.0.1:8080
jclouds.provider=filesystem
jclouds.identity=identity
jclouds.credential=credential
jclouds.filesystem.basedir=c:\temp_

but proxy started only on 8080 over http (not https).

What I missed?

p.s. **requestprivkey.pfx** - just a file with standard pfx-container that contains public and private keys. Can I use it (cant understand how to create jks)?

And, where i have to type Access key and Secret key like Amazon S3?

Thanx!!!

**Comment by andrewgaul** [comment]
Can you create a keystore.jks via the wiki instructions:

https://github.com/andrewgaul/s3proxy/wiki/SSL-support

**Comment by andrewgaul** [comment]
@Andrey198 did you resolve this issue?
