### ISSUE TITLE
Unknown parameters part-number-marker

### ISSUE THREAD

**Issue by kishore25kumar** [andrewgaul/s3proxy#162]
I am trying to use s3proxy to save objects to Azure blobstore. Here is the code

```java
TransferManager transferManager = new TransferManager(amazonS3Client);
String file = MultiPartUpload.class.getClassLoader().getResource(fileName).getFile();
Upload upload = transferManager.upload(bucketName, keyName, new File(file));
upload.waitForUploadResult();
```

I am getting the following error at s3proxy:

```
Unknown parameters part-number-marker with URI /test-bucket-kishore/test-video.mp4
 501 NotImplemented A header you provided implies functionality that is not implemented. {}
```

Right now I added part-number-maker to `SUPPORTED_PARAMETERS` and its working. What is the actual fix for it?

**Comment by andrewgaul** [comment]
How big is your file and which version of aws-java-sdk do you use?

**Comment by kishore25kumar** [comment]
File size is 43 MB. I am using aws-java-sdk version is 1.11.33

**Comment by andrewgaul** [comment]
S3Proxy does not support ListParts pagination but it can support this initial no-op value.  I will merge a fix this weekend.

**Comment by shenghu** [comment]
@andrewgaul can S3Proxy support 10GB+ file?

**Comment by andrewgaul** [comment]
@shenghu S3Proxy supports 5 GB files via single-part upload and 5 TB files via multi-part upload.  These limits match AWS service and we could increase or decrease them to match the backend object store.
