### ISSUE TITLE
Signed URL not working

### ISSUE THREAD

**Issue by kishore25kumar** [andrewgaul/s3proxy#164]
I am trying to upload a content to azure using aws signed urls. I was able to generate the signed url but when I am posting data to it I am getting 403 forbidden error.

Here is the link to code where it is throwing the error 
https://github.com/andrewgaul/s3proxy/blob/master/src/main/java/org/gaul/s3proxy/S3ProxyHandler.java#L364

How can I resolve this?

**Comment by kishore25kumar** [comment]
Its working when I set the S3SignerType in ClientConfiguration

**Comment by kishore25kumar** [comment]
We require support for Support V4 Signed URLs

**Comment by andrewgaul** [comment]
Duplicate of #160.
