### ISSUE TITLE
s3 multipart upload to openstack swift changes file checksum

### ISSUE THREAD

**Issue by wnieminen** [andrewgaul/s3proxy#166]
I tried to use the multi-part upload via s3proxy to openstack swift. But the file gets corrupted / changed on the way and the checksum of uploaded file in openstack differs from the original file. The size of files are the same. Is this known issue? Regular uploads worked fine. 

I tested it with 1.5.0 prelease.

**Comment by andrewgaul** [comment]
Can you provide a complete test case?  I just ran the S3Proxy tests against Rackspace Cloud Files (backed by OpenStack Swift) and all multi-part tests succeed.

**Comment by wnieminen** [comment]
Upload a large file using S3 browser http://s3browser.com/ via S3 proxy to Swift. Download the file directly from Swift using Cyberduck. Cyberduck fails with error message: "Mismatch between MD5 hash <correct md5 sum> of downloaded data and ETag <incorrect md5 sum> returned by the server."

**Comment by tibbes** [comment]
@wnieminen, that may be a Cyberduck bug - for large files the S3 ETag *is not* the MD5 of the content. Have you actually manually compared the original and downloaded file?

**Comment by wnieminen** [comment]
It propably is a cyberduck bug.

**Comment by andrewgaul** [comment]
There is not enough for me to investigate here, but Swift does not quote ETags while S3 does so you might want to investigate further and ask the Cyberduckies to ignore quotes within ETags.
