### ISSUE TITLE
Be able to get presigned url of object storage

### ISSUE THREAD

**Issue by shenghu** [andrewgaul/s3proxy#171]
@andrewgaul suppose the deployment is app<->s3proxy<->aws. app need get pre-signed url issued by aws. Can S3Proxy provide it?

**Comment by andrewgaul** [comment]
AWS does not issue pre-signed URLs; applications generate these using their AWS credentials and vend the URLs to a client.  AWS/S3Proxy interprets these URLs and compares the account and calculated signature against the local credentials.  S3Proxy supports v2 signed URLs but has not implemented v4 yet #160.

**Comment by shenghu** [comment]
@andrewgaul so when app generates pre-signed urls, it uses credentials of s3proxy, right? If app need generate pre-signed urls for aws, it needs know aws' credentials. If so, can s3proxy return aws' pre-signed url? We want the download (using pre-signed url) to bypass s3proxy for performance consideration.

**Comment by andrewgaul** [comment]
How would the application ask S3Proxy for this URL?  When the application requests an S3Proxy signed URL, S3Proxy responds with an HTTP 307 with the backend AWS signed URL?

**Comment by shenghu** [comment]
So I think of a way not to change s3proxy. But making change in the outer wrapper. i.e. to use a header to tell the proxy to generate presigned url for object storage.
