### ISSUE TITLE
Multipart failure

### ISSUE THREAD

**Issue by tibbes** [andrewgaul/s3proxy#172]
I think I've observed an instance of the recently added multipart upload support not working.

To reproduce:
- Use s3proxy 1.5.1 with the following s3proxy.conf
  ```
  s3proxy.authorization=none
  s3proxy.endpoint=http://127.0.0.1:9000
  jclouds.provider=filesystem
  jclouds.filesystem.basedir=/path/to/test/s3
  ```
- Use the latest Java Amazon SDK (aws-java-sdk-1.11.56.jar)
- Run this Java program (imports omitted for brevity):
  ```
	public static void main(String[] args) {
		AmazonS3Client client = new AmazonS3Client(new BasicAWSCredentials("test", "test"));
		client.setEndpoint("http://localhost:9000");
		client.setS3ClientOptions(S3ClientOptions.builder().setPathStyleAccess(true).build());

		if (client.doesBucketExist("test"))
			System.out.println("Bucket 'test' exists");
		else {
			System.out.println("Making bucket 'test'");
			client.createBucket("test");
		}
		System.out.println(client.listBuckets());
		client.putObject("test", "goodbye", "Goodbye, World!");

		System.out.println(client.getObjectMetadata("test", "goodbye").getContentMD5());
	}
  ```

s3proxy throws an exception with the message `Content-Length mismatch, actual: 187 expected: 15`. Changing the `setS3ClientOptions` line to `disableChunkedEncoding()` makes the program work.

**Comment by andrewgaul** [comment]
@tibbes I tried to reproduce your symptoms but could not.  We have a test `S3AwsSdkTest.testBigMultipartUpload` which tests similar functionality.  Could you modify this to exhibit your symptoms or encapsulate your code as a new test so that I can run it?  Either send a pull request or just point me at your branch.

**Comment by tibbes** [comment]
Turns out the problem was the mismatch between `s3proxy.authorization=none` (in `s3proxy.conf`) and `new BasicAWSCredentials(..., ...)`.

**Comment by andrewgaul** [comment]
@tibbes I don't follow -- when I set my `s3proxy.authorization=none` and `s3proxy.identity=fail` all my tests succeed with any authentication.
