### ISSUE TITLE
md5 validation at aws client sdk

### ISSUE THREAD

**Issue by kishore25kumar** [andrewgaul/s3proxy#192]
In the current usage of s3 proxy, we have to disable md5 validation in put object and get object. And we are using azure backend using s3 proxy. And for us, md5 validation is important at the client side. Is there any way we can get the md5 of the object while connecting to azure backed using s3proxy. What does it take to support it in s3 proxy. I have also raised the issue in jclouds regarding the same thing.

**Comment by andrewgaul** [comment]
Azure put object response does not return the ETag as an MD5 so there is no way to support this, as previously discussed in #96.  You can provide a MD5 in the client request and the server will reject corrupt blobs.

**Comment by kishore25kumar** [comment]
@andrewgaul you have mentioned we can map content-md5 to etag for all operations except conditional get

Here is one of your comment from the issue 99
After offline discussion with @kahing, we believe that S3Proxy could mimic S3 more closely when using the Azure backend. All of the relevant Azure operations, e.g., put blob, get blob, head blob, list blob, return both Content-MD5 and ETag. Thus we could map the former to the latter for all operations except for conditional GETs where we must issue our own HEAD request before the conditional GET. Note that some of these require specifying a recent Azure API version which jclouds already does.

Is this still possible?

What is the solution for integrity check for get blob?

**Comment by andrewgaul** [comment]
Azure will not provide `Content-MD5` in every situation, for example you must provide it with put object and put block list calls for subsequent get blob to return it:

https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/17/windows-azure-blob-md5-overview/

What should S3Proxy set ETag to in this situation?  We would have to do the suggested mapping for conditional get and copy although this is straightforward.  Does multipart upload pose any challenges given that the MD5 for S3 MPU is a merkle tree?  What about when S3Proxy implicitly create an MPU for large single-part uploads?

**Comment by kishore25kumar** [comment]
Thanx for the inputs. I wanted to deep dive into this md5 thing and see if we could get a solution for integrity check when using azure blob as the backend. For us integrity check is kind of mandatory.

Here are the scenarios I am going to go deep in

1. Simple Put blob
2. Simple Get blob
3. Multi-part upload
4. Conditional get
5. S3 proxy making MPU for large single part upload

Please let me know if I am missing anything here.
