### ISSUE TITLE
How to stub a response

### ISSUE THREAD

**Issue by RaviH** [andrewgaul/s3proxy#198]
I am using this library in a Java project and want to stub a response. Something like `do this when this happens`. Can you please point me to a documentation as to how to do it?

**Comment by andrewgaul** [comment]
@RaviH S3Proxy includes a few middlewares such as [eventual consistency emulation](https://github.com/andrewgaul/s3proxy/wiki/Middleware---eventual-consistency) and [large object mocking](https://github.com/andrewgaul/s3proxy/wiki/Middleware-large-object-mocking) which modify behavior.  You can do the same by providing a forwarding `BlobStore` to `S3ProxyBuilder.blobStore`.
