### ISSUE TITLE
Ds3proxy.virtual-host change causing Signature errors

### ISSUE THREAD

**Issue by danielrife** [andrewgaul/s3proxy#211]
The recent commit https://github.com/andrewgaul/s3proxy/commit/16af493cad28ab23c3c1abb128b4db3b405f25e9
caused all my builds to fail with 
`<autogenerated>:14: err: SignatureDoesNotMatch: Forbidden`

Can this change be made to default to a previous setup, or does a new env input need to be provided?

**Comment by andrewgaul** [comment]
6b30e6612779e54c1741e522a09d6bd6b2dd31b4 should fix this and Travis updated the Docker image.  Sorry about the breakage and thanks for your feedback!
