### ISSUE TITLE
V4 POST uploads

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#212]
Presently this fails due to not parsing out and verifying the V4 signature.

**Comment by michaelwittig** [comment]
I just ran into this today. Is this something you are working on already @andrewgaul ? Otherwise I could give it a try...

**Comment by andrewgaul** [comment]
Could you try to add support to `S3ProxyHandler.handlePostBlob`?  The authentication code is a little messy but otherwise straightforward.  Here is a reference to follow:

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html
