### ISSUE TITLE
maven build failing - Failure to find org.apache.jclouds.labs:glacier:jar:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by greenstevester** [andrewgaul/s3proxy#37]
Hi Andrew, it just did a pull and tried to build your code locally with maven and got:

Failure to find org.apache.jclouds.labs:glacier:jar:2.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots 

Do you see this as well?

Regards,
Steve

**Comment by andrewgaul** [comment]
@greenstevester Travis CI seems to include the Apache snapshot repository by default and my local install of jclouds masked these symptoms.  I fixed this in pom.xml; thanks for reporting this issue!
