### ISSUE TITLE
maven shade v2.3 plugin is broken

### ISSUE THREAD

**Issue by greenstevester** [andrewgaul/s3proxy#38]
Hi Andrew, 

FYI: maven shade v2.3 plugin is broken see https://jira.codehaus.org/browse/MSHADE-183

I patched it locally, bumped up the plugin version to 2.3.1 and your pom ran fine!

Regards,
Steve

**Comment by andrewgaul** [comment]
@greenstevester I can reproduce these symptoms with Maven 3.2.5.  I will watch the upstream issue and upgrade to the next version of Shade when released.  In the mean-time downgrading to Maven 3.2.3 works around this issue.

**Comment by greenstevester** [comment]
Thanks for the quick response and work-around!

On 24 Jan 2015, at 13:06, Andrew Gaul <notifications@github.com> wrote:

> @greenstevester I can reproduce these symptoms with Maven 3.2.5. I will watch the upstream issue and upgrade to the next version of Shade when released. In the mean-time downgrading to Maven 3.2.3 works around this issue.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



Steven Greensill
Technoparkstrasse 8, 
8005 Zürich, 
Switzerland
t: +41 76 474 6784
e: steve@greensill.net

**Comment by andrewgaul** [comment]
This issue is causing Travis CI builds to fail:

https://travis-ci.org/andrewgaul/s3proxy/builds/50581682
