### ISSUE TITLE
bucket and object canned ACLs

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#44]
jclouds 1.9.0 will add bucket and object ACL support via [JCLOUDS-660](https://issues.apache.org/jira/browse/JCLOUDS-660) and [JCLOUDS-732](https://issues.apache.org/jira/browse/JCLOUDS-732).  S3Proxy can easily add get and set ACL RPCs but needs some additional work to pass an authentication context through for unauthenticated reads.

**Comment by markgaylard** [comment]
Does this mean that anonymous reads cannot be done at the moment? I'm using jclouds/filesystem and setting the acl on the objects as 'public-read' but when I request them I get '403 AccessDenied Forbidden null null' logged.

**Comment by andrewgaul** [comment]
@markgaylard Presently public access does not work.  I have a work-in-progress commit at https://github.com/andrewgaul/s3proxy/tree/anonymous-access but have not yet revisited this.

**Comment by andrewgaul** [comment]
@kahing Multiple blobstore backends conflict with anonymous access.  Presently we look up the correct backend using the identity which does not exist in the anonymous context.  Any suggestions on how to support both?

**Comment by kahing** [comment]
https://github.com/andrewgaul/s3proxy/pull/59/files

**Comment by andrewgaul** [comment]
Unfortunately we collide with the two definitions of anonymous access -- S3Proxy has an anonymous mode which disables authentication for all requests but we are trying to support per-request anonymous access based on ACLs in this issue.

**Comment by andrewgaul** [comment]
@markgaylard Should be fixed now, please share your feedback.
