### ISSUE TITLE
Support service paths

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#48]
Some object stores like Eucalyptus Walrus use service paths, e.g., `https://host/services/Walrus/container-name/blob-name`.  S3Proxy supports these for the S3 back-end via `jclouds.s3.service-path`; it should support them for the front-end as well.

**Comment by shenghu** [comment]
@andrewgaul yes, I need this as well. I mean s3proxy is possible to be deployed as http://host:port/contextroot/bucket/key. Right now, I use a wrapped request which remove service path in request.getUri(). But I think it is better that S3ProxyHandler can accept a property and remove it from request.getUri().

**Comment by andrewgaul** [comment]
Apache jclouds support this on the client side for Eucalyptus and its `/services/Walrus` service path.  Thus we can use it to write a test for your use case via `PROPERTY_S3_SERVICE_PATH` override.  Could you investigate adding this functionality?

**Comment by shenghu** [comment]
OK. I can do this. BTW, is jclouds active now? I'm thinking to use jclouds as client vs using s3 sdk directly in our app to connect to s3proxy. Benefits of using jclouds are 1) unit testing w/ filesystem; 2) common API to support both s3 and openstack.

**Comment by andrewgaul** [comment]
jclouds is active and just released 2.0.0.  S3Proxy uses it for all backend interactions.
