### ISSUE TITLE
Release S3Proxy 1.5.0

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#55]
Master has three important features: v4 signing #24, native multi-part upload #2, and native copy object #46.  These require pre-release jclouds and we must wait until its next release.

**Comment by stephzylstra** [comment]
Is there an ETA for this release?

**Comment by andrewgaul** [comment]
This release is blocked on jclouds 2.0.0 which should release mid-February:

https://www.mail-archive.com/dev@jclouds.apache.org/msg06293.html

**Comment by stephzylstra** [comment]
Fantastic, thank you!
