### ISSUE TITLE
Bucket in hostname on filestore provider

### ISSUE THREAD

**Issue by leonm** [andrewgaul/s3proxy#79]
According to the S3 api docs the bucket name should be part of the hostname of the URL ( http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html#RESTBucketGET-responses-examples ) In other words the bucket name is part of the domain and not part of the path.

So I added a couple of /etc/hostfile entries to test this behaviour of s3proxy with a filestore provider:
```
127.0.0.1       s3
127.0.0.1       bucket1.s3
```
I used a pretty simple config file:
```
s3proxy.authorization=none
s3proxy.endpoint=http://s3:8080
jclouds.provider=filesystem
jclouds.identity=identity
jclouds.credential=credential
jclouds.filesystem.basedir=/tmp/s3
```

I created the `/tmp/s3` and `/tmp/s3/bucket1` directories.

Then used curl to test the config.  I expected `curl http://s3:8080/` to give me a list of buckets and `curl http://bucket1.s3:8080/` to give me a list of objects in bucket1.  However both these give me a list of buckets.  (It works if I do `curl -v http://s3:8080/bucket1/`)

Is this expected behaviour?

**Comment by andrewgaul** [comment]
Could you try setting `s3proxy.virtual-host=s3` in your properties file?

**Comment by leonm** [comment]
That works perfectly, thank you very much.

Is there somewhere I can write this up so that those after me have an example to work from?
