### ISSUE TITLE
Multipart upload results in "Form too large" exception

### ISSUE THREAD

**Issue by alexmojaki** [andrewgaul/s3proxy#80]
I tried performing a multipart upload via the Java AWS SDK but jetty threw an exception:
```
20:06:58.167 [qtp792782299-17 - /s3proxy-596354326/stuff?uploadId=EXAMPLEJZ6e0YupT2h66iePQCc9IEbYbDUy4RTpMeoSMLPRp8Z5o1u8feSRonpvnWsKKG35tI2LB9VDPiCgTy.Gq2VxQLYjrue4Nq.NBdqI-dc5b1fe8-31ea-4902-9de1-51187d9c718e&partNumber=5001] WARN  org.eclipse.jetty.server.HttpChannel - /s3proxy-596354326/stuff?uploadId=EXAMPLEJZ6e0YupT2h66iePQCc9IEbYbDUy4RTpMeoSMLPRp8Z5o1u8feSRonpvnWsKKG35tI2LB9VDPiCgTy.Gq2VxQLYjrue4Nq.NBdqI-dc5b1fe8-31ea-4902-9de1-51187d9c718e&partNumber=5001
java.lang.IllegalStateException: Form too large: 10485768 > 200000
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:364)
```
The part is about 10 MB. Am I doing something wrong? The setup for the proxy was copied directly from `S3AwsSdkTest.java` and the client was set up as follows:
```
AmazonS3Client client = new AmazonS3Client(awsCreds);
        client.setEndpoint(s3Endpoint.toString());
        client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
```
I didn't include the signer override part because I didn't know what algorithm to put in there.

As far as I understand the "Form too large" error indicates that jetty is configured this way. Do I have to configure it myself? If so, how? Moreover, why? It seems surprising that the setup wouldn't accept large packets by default, to the extent that I'm convinced I've done something else wrong.

**Comment by andrewgaul** [comment]
Jetty has a default limit of 200,000 bytes:

https://wiki.eclipse.org/Jetty/Howto/Configure_Form_Size

I am having trouble verifying this fix -- could you try setting the `org.eclipse.jetty.server.Request.maxFormContentSize` system property and report your results?

**Comment by alexmojaki** [comment]
Ah, I didn't see anything about system properties, just XML files. Anyway, I set the property, and I even printed it out to be sure, but the error is still there.

**Comment by alexmojaki** [comment]
I looked into the code and found it doing this:
```
    int maxFormContentSize = -1;
    int maxFormKeys = -1;

    // This is false
    if (_context != null)
    {
        // This is where it would get the system property but it doesn't get here
        maxFormContentSize = _context.getContextHandler().getMaxFormContentSize();
        maxFormKeys = _context.getContextHandler().getMaxFormKeys();
    }

    if (maxFormContentSize < 0)
    {
        // I guess this is where it tries to find XML configuration
        Object obj = _channel.getServer().getAttribute("org.eclipse.jetty.server.Request.maxFormContentSize");
        // But it's null so it uses the default
        if (obj == null)
            maxFormContentSize = 200000;
```

**Comment by alexmojaki** [comment]
Hey, was there any progress on this? I don't want to nag but I got really hopeful when you responded so quickly the first time.

**Comment by andrewgaul** [comment]
@alexmojaki I added some sanity checking and a test for 10,000 parts.  Could you retest with master and include a test case if you still encounter issues?

**Comment by alexmojaki** [comment]
Hey, thanks for getting back to me. Unfortunately nothing seems to have changed but I've added the tests.

**Comment by andrewgaul** [comment]
@alexmojaki Thank you for providing a test case!  I have investigated this more and found that Jetty incorrectly parses the put multipart object because the AWS SDK provides the incorrect Content-Type: application/x-www-form-urlencoded; charset=utf-8.  I am still investigating this but please see https://github.com/andrewgaul/s3proxy/commit/82f67359bfffe44bb2548171dc498198f9bc1635 for a workaround.

**Comment by alexmojaki** [comment]
Awesome! The workaround solved my problem. Now my library can be tested properly. Thanks so much for sorting this out. The library is here in case you're interested: https://github.com/alexmojaki/s3-stream-upload

**Comment by andrewgaul** [comment]
@alexmojaki Thanks for the reference!  Many jclouds users have asked for a similar feature over the years although we have not yet implemented it.  I recently made some changes to jclouds multi-part upload support which should allow this in the future, though.
