### ISSUE TITLE
swift: how to select region? It is always the first entry selected.

### ISSUE THREAD

**Issue by Dexus** [andrewgaul/s3proxy#81]
```
main o.j.l.s.i.GetRegionIdMatchingProviderURIOrNull:74 |::] failed to find key for value  https://auth.cloud.ovh.net/v2.0 in {GRA1=https://storage.gra1.cloud.ovh.net/v1/AUTH_xxx, BHS1=https://storage.bhs1.cloud.ovh.net/v1/AUTH_xxx, SBG1=https://storage.sbg1.cloud.ovh.net/v1/AUTH_xxx}; choosing first: GRA1
```
my config:
```
s3proxy.endpoint=http://127.0.0.1:8080
s3proxy.authorization=aws-v2
s3proxy.identity=xxx
s3proxy.credential=xxx
jclouds.provider=openstack-swift
jclouds.endpoint=https://auth.cloud.ovh.net/v2.0
jclouds.api=swift
jclouds.regions=SBG1
jclouds.identity=1xx9:xxx
jclouds.credential=xxx
```

**Comment by andrewgaul** [comment]
@Dexus S3Proxy previously lacked support for specifying regions for Swift-based object stores.  I added support and an example for Rackspace Cloud Files here:

https://github.com/andrewgaul/s3proxy/wiki/Provider-examples#rackspace-cloud-files

In the current implementation, you specify a single `jclouds.region` (note not plural).  Note that Swift has multiple ways of specifying regions so you may need to experiment with different endpoints.

**Comment by PolSpock** [comment]
Hello,
I have the same problem :/

```
./s3proxy --properties test.conf 
[s3proxy] W 02-14 14:53:56.630 main o.j.l.s.i.GetRegionIdMatchingProviderURIOrNull:74 |::] failed to find key for value https://auth.cloud.ovh.net/v3/ in {DE1=https://storage.de1.cloud.ovh.net/v1/AUTH_XXXX, UK1=https://storage.uk1.cloud.ovh.net/v1/AUTH_XXXX, SBG3=https://storage.sbg3.cloud.ovh.net/v1/AUTH_XXXX, WAW1=https://storage.waw1.cloud.ovh.net/v1/AUTH_XXXX, BHS3=https://storage.bhs3.cloud.ovh.net/v1/AUTH_XXXX, GRA3=https://storage.gra3.cloud.ovh.net/v1/AUTH_XXXX}; choosing first: DE1
```

OVH is mutli region
Someone can help me ? 😄 

Regards,

**Comment by gaul** [comment]
Does setting `jclouds.region` allow you to select the region?  See [this example](https://github.com/gaul/s3proxy/wiki/Storage-backend-examples#swift-keystone-v20).

**Comment by PolSpock** [comment]
Yes, i have tested with Keystone v2.0 & v3.0.
I've tried `jclouds.region` & `jclouds.regions` but it doesn't take my settings
