### ISSUE TITLE
Multipart cleanup

### ISSUE THREAD

**Issue by auguster** [andrewgaul/s3proxy#88]
I noticed that when I send a file that triggers a multipart upload, after the upload some stuff remains.

For example, I have an empty file called `EXAMPLEJZ6e0YupT2h66iePQCc9IEbYbDUy4RTpMeoSMLPRp8Z5o1u8feSRonpvnWsKKG35t
I2LB9VDPiCgTy.Gq2VxQLYjrue4Nq.NBdqI-7e9ddb3d-b582-4e9f-b099-a824cedc87b4` that lies in the bucket next to the actual uploaded file.

This "junk file" is listed by `ls` and can be removed by `rm`

I used `release 1.4.0 jar` and `aws-cli/1.4.2 Python/3.4.2 Linux/3.16.0-4-amd64`

**Comment by andrewgaul** [comment]
https://github.com/andrewgaul/s3proxy/commit/5f1c4979eff4b9723edab7ba813a0a4f4f5223a7 fixed this although I am waiting for jclouds 2.0.0 before releasing S3Proxy 1.5.0.

**Comment by auguster** [comment]
Ok, thanks ;-)
