### ISSUE TITLE
multipart upload error with openstack-swift backend

### ISSUE THREAD

**Issue by dleute** [andrewgaul/s3proxy#91]
Current master is providing this error for a multipart upload using s3cmd:

ERROR: S3 error: 500 (Multiple entries with same key: 1=MultipartPart{partNumber=1, partSize=5242880, partETag=d2c07cca277ffb5924c4a77d12688bab} and 1=MultipartPart{partNumber=1, partSize=5242880, partETag=d2c07cca277ffb5924c4a77d12688bab}): 

I assume this is because of the partNumber mismatch. Reproducing this:

```
s3cmd put --multipart-chunk-size-mb=5 s3proxy s3://mybucket/whatever/s3proxy
s3cmd del s3://mybucket/whatever/s3proxy
s3cmd put --multipart-chunk-size-mb=5 s3proxy s3://mybucket/whatever/s3proxy
```

The above example seemingly uploads correctly. Then the delete seems to have deleted correctly. Then uploading another multipart upload to the same object id always fails.

Could you give me some feedback about how to debug and correct this? I realize it is likely to be an underlying jclouds issue.

Thanks!

--Derrek

**Comment by andrewgaul** [comment]
@dleute I reproduced your symptoms and it was caused by an underlying jclouds issue as you suspected.  Swift MPU has user-exposed parts and an explicit manifest, unlike S3.  When deleting the MPU manifest, S3Proxy currently does not remove the parts.  Subsequent uploads found these parts and erroneously included them in the current MPU.  I fixed this issue although S3Proxy should also clean up the MPU parts on delete.  The underlying jclouds fix will take a few hours to percolate out to the sonatype snapshot repository; please report back on whether this addresses your issue.  Thanks for reporting this!

**Comment by dleute** [comment]
Wow, that was fast! :) I will follow up monday after things update!

Will your fix deal with past issues? meaning I have a specific object id that I've been pushing multi-part uploads to for a while, attempting to delete, then trying again. So there are a lot of fragments out there. I  had just realized that the delete was probably only deleting the manifest, not the fragments.  Any recommendation about how to deal with that? Clearing out the container should be an option, just curious if your solution will deal with a problem when say a transfer fails and there is a chunk lying around.

On another note, I would love to be able to contribute on things like this. But I can't get maven to give me sources so I can update underlying libraries and test changes to my s3proxy code.

**Comment by andrewgaul** [comment]
New uploads will work correctly although you will still have the part litter that #92 tracks.  You can delete each part individually as a workaround for now.  If an application explicitly aborts a multipart upload S3Proxy should clean up all the litter.

Sorry I do not follow about the source code?  S3Proxy deploys the sources via maven-source-plugin; does this not work correctly?  Or do you have an issue with the underlying jclouds library?  You should be able to `git clone` if your IDE cannot find the sources.

**Comment by dleute** [comment]
maven says source jars are not available for 2.0.0-SNAPSHOT (see below)

FYI: I am not an experienced maven user. So I could just be failing to do something I should.

I will resort to git clone if I have to. But I believe that means I need to make my changes in the underlying library, bump the version (not sure how that works with SNOPSHOT) do a maven install and then maven compile on s3proxy? The idea being that my local maven repo will have my updated code.

Feel free to send me url's if I'm just missing basic maven capabilities.

```
[INFO] The following files have NOT been resolved:
[INFO]    org.apache.jclouds.provider:aws-s3:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:openstack-keystone:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds:jclouds-allblobstore:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.beanshell:bsh:jar:sources:2.0b4:test
[INFO]    org.apache.jclouds.api:s3:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds:jclouds-blobstore:test-jar:sources:2.0.0-SNAPSHOT:test
[INFO]    org.apache.jclouds.provider:rackspace-cloudfiles-us:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:s3:test-jar:sources:2.0.0-SNAPSHOT:test
[INFO]    org.apache.jclouds.api:filesystem:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds:jclouds-blobstore:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.driver:jclouds-slf4j:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.common:googlecloud:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:openstack-swift:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds:jclouds-core:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:oauth:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:atmos:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:rackspace-cloudfiles:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:rackspace-cloudidentity:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.common:openstack-common:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds:jclouds-core:test-jar:sources:2.0.0-SNAPSHOT:test
[INFO]    org.apache.jclouds.provider:rackspace-cloudfiles-uk:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:swift:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.api:sts:jar:sources:2.0.0-SNAPSHOT:compile
[INFO]    org.apache.jclouds.provider:azureblob:jar:sources:2.0.0-SNAPSHOT:compile
```

**Comment by khoah64** [comment]
Thanks for fixing it (in both s3proxy and jclouds) so fast!

**Comment by dleute** [comment]
I can confirm that it is working at this time! Thanks for the quick fix!

**Comment by nacx** [comment]
@dleute The missing jar sources issue was due to a misconfiguration in the jclouds builds that publish the snapshots to the Maven repo. It is now fixed and a new build is running, so the snapshots will be available in an hour or so, when the build completes.

**Comment by dleute** [comment]
Great! I'll give it a whirl as soon as I can. (That may be after thanksgiving)

Thanks!
