### ISSUE TITLE
Re-factoring question for s3proxy portability

### ISSUE THREAD

**Issue by dleute** [andrewgaul/s3proxy#93]
Our requirements are a bit different. We have to effectively re-write the incoming url to a different outgoing url for use with s3proxy (and swift on our backend).

I accomplished this by writing a HandlerWrapper that makes necessary changes and forwards those requests using setRequestURI (which seems to have disappeared in newer versions of jetty. that's another issue) onto S3ProxyHandler. This "works".

The intent was to write a wrapper that could do the job while modifying the underlying code as little as possible. Unfortunately I find myself having to pull functionality from inside the underlying S3ProxyHandler and put it in my wrapper. Things like support for virtual host style buckets and authentication need to happen in this wrapper layer. And, in fact, when they happen in my wrapper layer, they shouldn't happen in the underlying handler. In addition, jetty does not appear to allow you to change many aspects of the request.

What do you think about making s3proxy functionality into something a bit more like a library/utility. Much of the functionality could be abstracted out into helper functions and not directly implemented in S3ProxyHandler. In that way, the provided S3ProxyHandler could be more of a functional default behavior, but if you supply a different handler, you can override behavior easily.

If there is a mailing list or other place to discuss this more appropriate than here, please let me know.

@andrewgaul Thanks for all your help on this! If this is of interest to you, please let me know. I would be happy to setup a time to talk about it in depth.

--Derrek

**Comment by andrewgaul** [comment]
Could you use jclouds [ForwardingBlobStore](https://github.com/apache/jclouds/blob/master/blobstore/src/main/java/org/jclouds/blobstore/util/ForwardingBlobStore.java) to rewrite the request after S3Proxy has handled it?  You would subclass `ForwardingBlobStore`, rewrite the request in each method, then call the superclass `BlobStore` which forwards along to Swift or similar provider.  I use this technique in the currently uncommitted [EventualBlobStore](https://github.com/andrewgaul/s3proxy/tree/eventual-blobstore).

**Comment by dleute** [comment]
I need to dig into the code on that. It's an interesting idea. I'm not sure how to get my custom forwarding blob store to be used. Is it parameter of the s3proxy config somehow? Or do I still modify the core s3proxy classes to use it? One down side is it looks like a lot of changes compared to re-writing the incoming url.

I would still argue that a re-factor might be beneficial for other reasons.

My project hasn't gotten to this point, but forwarding to multiple different storage backends based on some selection criteria is a distinct possibility. Unless I am mistaken, the forwarding blob store would not work for that particular case as blob stores are configured for a single backend? Or the simpler case of mirroring to write to two different backends simultaneously. Right now I would split the stream and write to two S3ProxyHandler classes configured differently to do this. (I'm not sure of the actual technical feasibility, just an example of things I may have to think about in the near future)

Anyway, it's food for thought.

**Comment by andrewgaul** [comment]
I agree that configuration of rewrite rules is hard and configuration is the reason I have not merged the eventually consistent blobstore simulator in #65.  Perhaps a more general mechanism to configure multiple object stores would make this more obvious.  Happy to review any refactoring pull requests, especially those that improve the readability of the code or ease-of-use for users.

Can you expand a bit on your use case?  At Bounce Storage we use S3Proxy to implement object store mirroring, tiering, migration, etc. via the `ForwardingBlobStore` although we only use S3Proxy as one of our components.  These features add a lot of complexity since you generally want asynchronous updates and need to reconcile multiple stores.

**Comment by dleute** [comment]
Right now, our use case is to accept the s3 api and shard to multiple swift containers. At this time, there isn't more complexity than that. But performance is a huge concern. Right now a double auth is done by our wrapper, and then forwarded to s3proxy which checks our re-written auth (because of the path change). I'm trying to save every cycle I can.

More concrete requirements have not yet appeared. But doing this is not something that can currently be implemented "generically" in the existing s3proxy code base. I basically replaced the existing S3ProxyHandler with my own wrapper handler and forwarded to S3ProxyHandler.

My current goal is to make it easy to do such a change using the existing s3proxy code.

There is also the possibility of needing to port this to tomcat. That would require de-coupling s3proxy from Jetty. That is another reason for the question of making s3proxy functionality more like a library utility.

**Comment by andrewgaul** [comment]
Double-authentication should not be much overhead since HMAC is cheap...

Sharding sounds like a good use case for S3Proxy.  I am not clear on how invasive this would be and whether making S3Proxy more reusable in external projects might be a better path forward.  What do you think?

I like your idea of making S3Proxy more embeddable and allowing a pluggable HTTP server.  Most of the code uses generic servlets like `HttpServletRequest` but `S3ProxyHandler` does extend `org.eclipse.jetty.server.handler.AbstractHandler`.  Can you investigate how to abstract this?  Note that I would like the s3proxy *binary* to continue to work standalone, e.g., Main.java, although the `S3Proxy` *class* could become agnostic to the HTTP server and other details.

Please send pull requests with any needed refactoring or abstraction!

**Comment by dleute** [comment]
Double authentication has not had a measurable impact at this time. But I like clean elegant DRY code. And my own work doesn't qualify for that at the moment.

I think having a general library that can understand s3 requests could be quite useful. But I don't have a use case specifically for it. I could see an application or testing framework wanting to embed something that can understand the s3api but write out to any object store.

The biggest thing is the inputs need to be abstracted out as standard parameters. You won't get a Request object, you will get an array of parameters or explicit parameters in the function calls. The same thing will need to happen for config (and I encourage a full on config system, possibly yaml based).

I completely agree on the binary. This should really be at least 2 maven projects. One is the core library that does all the work. The other is the cli server. This has the benefit of allowing me to create a lightweight wrapper in my own project (probably based on the cli library initially).

Break down like this:

s3proxy-cli: Reads config files. Writes config to library. Uses Jetty Handlers like today. Forwards necessary parameters from the base jetty wrappers into s3proxy-lib commands.

s3proxy-lib: Is a collection of re-usable functions that take explicit parameters (instead of Request objects). Probably modeled after S3ProxyHandler today with all references to Jetty abstracted as explicit parameters.

In this way, in a re-write situation, I only care about re-writing the variables from the request that I care about (In fact, making this happen in jetty has been a real sticking point especially across different versions of jetty). If the internal functionality is abstracted, things like "auth" can be skipped internally as it's the Handler's responsibility to do those things (by calling s3proxy-lib functions). If the handler passes on the request, you can assume sufficient auth has happened.

There is some question has to who would be responsible for returning status codes. Theoretically, this is an http implementation issue, so it should be the handler. Example: if function X fails, return code Y. But it's not always that simple.

If nothing else this would lead to more elegant/maintainable separation of code. And that's a good thing.

How do you feel about it?

**Comment by kahing** [comment]
I am wary of massive rewrites unless there's a specific use-case in mind, in my experience that rarely leads to an API that future users can use. 

That said, you can also implement sharding using the existing `BlobStoreLocator` interface. It's slightly more wasteful than implementing your own `ForwardingBlobStore`, but as long as you are not copying the streams the cost is likely trivial.

**Comment by dleute** [comment]
@kahing: I'm still not sure how to implement that.

One of my goals in suggesting this re-factoring, is to make the base functionality more flexible without having to re-compile tho core code.

If I do BlobStoreLocator or ForwardingBlobStore, I still need to branch and maintain my own version of s3proxy to override various aspects of S3ProxyHandler don't I?

This re-factoring should first and foremost allow me to maintain my own extensions without maintaining the core code myself. Secondary effects of that are cleaner code and more flexible usage. So, in my case, I would like to re-factor enough to allow a WrapperHandler to use underlying library functions instead of having them all embedded in an S3ProxyHandler class.

I'll see if I can provide some examples shortly.

**Comment by kahing** [comment]
S3ProxyHandler has a setBlobStoreLocator() function that you can call without modifying S3Proxy. Obviously you can't rely on `org.gaul.s3proxy.Main` anymore and will need your own init code, but that's the case if you refactor s3proxy anyway.

**Comment by kahing** [comment]
Ignore my comment about `BlobStoreLocator`, it's easier to just do it within `ForwardingBlobStore`.

**Comment by dleute** [comment]
@kahing: So I would create my own blobstore and set it from my custom wrapper. If the blobstore persists, which it seems like it would, then I might be able to get rid of my custom wrapper. I will take a look and see if it makes sense to migrate my code.

It would still be nice to have a separation of functionality. Even in this example I have to modify the core code and then maintain it. If the core s3proxy functionality were abstracted out, I would just be tied to a maven dependency and only my own wrapper handler.

Anyway, like I said, I'll see if I can provide some examples.

**Comment by andrewgaul** [comment]
Closing this as there is no actionable request.
