### ISSUE TITLE
Anonymous access mode cannot list a private access bucket

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#94]
Anonymous access configuration should skip `doHandleAnonymous` handling which only allows access to public-read buckets and keys.  Discovered by @ritazh and @sedouard.

**Comment by ritazh** [comment]
@andrewgaul Working on a fix now.

**Comment by ritazh** [comment]
@andrewgaul Just to confirm, should the expected behavior be that when anonymous access is configured, handler should return all buckets and keys?

**Comment by andrewgaul** [comment]
@ritazh Great! Yes anonymous access configuration should allow reading all buckets and keys.

**Comment by ritazh** [comment]
@andrewgaul in the code block below:
```
 // anonymous request
        if ((method.equals("GET") || method.equals("HEAD") ||
                    method.equals("POST")) &&
                request.getHeader(HttpHeaders.AUTHORIZATION) == null &&
                request.getParameter("AWSAccessKeyId") == null &&
                defaultBlobStore != null)
```
The handler is getting anonymous access configuration from the http request header, instead of the `s3proxy.authorization` setting in the config file. Can you please confirm where this value should come from?

**Comment by andrewgaul** [comment]
Yes, S3Proxy should skip over this logic when configured for anonymous access mode.
