### ISSUE TITLE
AWS SDK upload fails with Azure backend

### ISSUE THREAD

**Issue by ritazh** [andrewgaul/s3proxy#96]
Using this sample code here:
https://github.com/aws/aws-sdk-java/blob/master/src/samples/AmazonS3/S3Sample.java#L119

Error:
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1398): Input is expected to be encoded in multiple of 2 bytes but found: 17

File was uploaded successfully, but ends in exception.

Same test runs successfully against AWS S3.

I see this PR added etag support for AzureBlob. https://github.com/jclouds/jclouds/pull/716/files

**Comment by ritazh** [comment]
Adding more info, in `com.amazonaws.util`, `Base16Codec` is expecting an even length.

```
public byte[] decode(byte[] src, final int length)
    {
        if (length % 2 != 0) {
            throw new IllegalArgumentException(
                "Input is expected to be encoded in multiple of 2 bytes but found: "
                + length
            );
        }
        final byte[] dest = new byte[length / 2];
```

**Comment by kahing** [comment]
s3 expects a regular PUT to return etags as the md5sum of the blob encoded in base16, and the `AmazonS3Client` is probably verifying the md5sum from the response. Maybe S3Proxy can return Content-MD5 as etags instead?

**Comment by ritazh** [comment]
Yes I think that would work.

**Comment by kahing** [comment]
@andrewgaul pointed out to me that munging with etags will cause problems with conditional GETs. And the option in the sdk to disable the check is not implemented correctly: https://github.com/aws/aws-sdk-java/blob/bb9e0be441afb5658f0edbbd19bcf27e2fac4105/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L452

**Comment by ritazh** [comment]
I'm trying to figure out why jcloud returns an ETag of 17 bytes for Azure blob. Any suggestions?

**Comment by kahing** [comment]
According to https://github.com/jclouds/jclouds/pull/716/files#diff-e724f00ae88c3a1a9ec1ddbe252a3bccL10 Azure etags looks like 0x8CACB9BD7C1EEEC which is 17 bytes.

**Comment by andrewgaul** [comment]
Azure returns a non-MD5 ETag.  We should not change the meaning of this since ETag are used for conditional GETs.  We could elide non-MD5 ETag but I do not believe that we should recalculate the MD5 in-flight to fake the ETag.  I opened a pull request against aws-sdk-java to control their behavior.

**Comment by andrewgaul** [comment]
After offline discussion with @kahing, we believe that S3Proxy could mimic S3 more closely when using the Azure backend.  All of the relevant Azure operations, e.g., put blob, get blob, list blob, return both Content-MD5 and ETag.  Note that some of these require specifying a recent Azure API version which jclouds already does.  Thus we could map the former to the latter for all operations except for conditional GETs where we must issue our own HEAD request before the conditional GET.

@ritazh Would you like to try implementing this?  Note that we want to use the server values and not calculate these on the proxy side.

**Comment by ritazh** [comment]
Sure thing. Let me take a closer look this weekend and get back to you.

**Comment by ritazh** [comment]
@andrewgaul @kahing let me know when you guys have sometime to talk today or tomorrow.

**Comment by kahing** [comment]
Ideally we would stay within the BlobStore  interface, is there something that you need that's not in the generic interface?

**Comment by ritazh** [comment]
Just trying to clarify what Andrew meant by "Note that some of these require specifying a recent Azure API version which jclouds already does." I see that jclouds is using the Azure blob storage REST API to communicate with Azure backend. In terms of what I can implement here, are you guys thinking of using Azure Java SDK in S3Proxy specifically in `S3ProxyHandler` to handle put, get, head, list operations?

**Comment by kahing** [comment]
Please don't use the azure sdk. According to https://msdn.microsoft.com/en-us/library/dd179451.aspx Azure only generates the content md5 header if the version requested is new enough, and that was what @andrewgaul was referring to.

**Comment by ritazh** [comment]
Okay. Thanks for clarifying.

**Comment by kahing** [comment]
To elaborate more, in each of the put/get/etc functions we should change as little code as possible. For instance, in handleGetBlob(), we can check if the provider is azure, and also conditional if-match/if-not-match is used, and only then handle the get in another path.

**Comment by ritazh** [comment]
Hey guys, need some guidance here. I noticed that after I call `handleGetBlob`, jclouds returns a response that contains `Content-MD`, then from the log, I see that jclouds `invoking GetContainerACL` and creates a HEAD request, which returns a response that does not contain `Content-MD`. Since I need `Content-MD` from a GET request, is there a way to control this behavior from jclouds? Thank you!

**Comment by andrewgaul** [comment]
You will likely need to modify jclouds to populate this field.  You can follow the chain of logic from `AzureBlobStore.blobMetadata` to `AzureBlobToBlob.apply` and finally `BlobPropertiesToBlobMetadata.apply`.

**Comment by andrewgaul** [comment]
@ritazh AWS SDK for Java 1.10.37 can disable the MD5 check on PUT via setting the `com.amazonaws.services.s3.disablePutObjectMD5Validation` system property.  Does this satisfy your application?

**Comment by ritazh** [comment]
@andrewgaul Thanks for looking into this. Looks like using the `disablePutObjectMD5Validation` flag disabled the MD5 check. If I need to enable MD5 check for Azure, how would I do that?

**Comment by andrewgaul** [comment]
`S3AwsSdkTest` disables the check but S3Proxy itself cannot influence the client-side behavior.  If you want to experiment with the test you can remove "azureblob" from `BLOBSTORE_OPAQUE_ETAG`.

**Comment by andrewgaul** [comment]
Closing since we have a workaround.
