### ISSUE TITLE
Support Backblaze B2

### ISSUE THREAD

**Issue by pjz** [andrewgaul/s3proxy#98]
Docs are [here](https://www.backblaze.com/b2/docs/).

**Comment by andrewgaul** [comment]
Needs upstream jclouds support tracked by [JCLOUDS-1005](https://issues.apache.org/jira/browse/JCLOUDS-1005).

**Comment by tarikd** [comment]
:+1:

**Comment by andrewgaul** [comment]
`b2_upload_file` requires a `X-Bz-Content-Sha1` header instead of the optional `Content-MD5` header S3 uses.  Thus S3Proxy would have to buffer all uploads to calculate the SHA-1 then send the payload the B2.

**Comment by michaelruge** [comment]
Any update on this?

**Comment by andrewgaul** [comment]
Please share general feedback in this issue and any specific problems in new issues.  B2 has some restrictions documented here:

https://github.com/andrewgaul/s3proxy/wiki/Storage-backend-compatibility#b2
