### ISSUE TITLE
Multipart upload fails with part-number-marker not implemented

### ISSUE THREAD

**Issue by ritazh** [andrewgaul/s3proxy#99]
I'm testing POST upload when file size is ~17MB. This triggers `handleInitiateMultipartUpload`, which returns `InitiateMultipartUploadResult` with `UploadId`. Then a new GET request is called with `part-number-marker=0`, which returns this error: "Unknown parameters part-number-marker". I noticed that jclouds `uploadMultipartPart` does not take in `part-number-marker`. Should this be added to S3Proxy or jclouds?

This is the client side code:
```
TransferManager tm = new TransferManager(s3);     
Upload upload = tm.upload(bucketName, key, new File(filePath));
```

**Comment by ritazh** [comment]
In a different test, I'm using `UploadPartRequest` similar to the `testBigMultipartUpload` [test](https://github.com/andrewgaul/s3proxy/blob/50a302436271ec46ce81a415b4208b9e14fcaca4/src/test/java/org/gaul/s3proxy/S3AwsSdkTest.java#L214), but with multiple `UploadPartRequest`, then only the first `UploadPartRequest` actually works. All subsequent UploadPartRequests are processed but blob is not actually uploaded. It's possible that I may have missed something. 

My test with a file of size 17MB, part size of 10MB. The expected behavior should be after `CompleteMultipartUploadRequest`, the entire 17MB file should be uploaded. The actual is a blob of size a little less than 10MB was uploaded as a result from the first `UploadPartRequest`. Yet a new ETag was returned for both `UploadPartResult`. From S3Proxy log, seems both requests for partnumber 1 and 2 have been processed properly. 
```
UploadPartRequest uploadRequest1 = new UploadPartRequest()
                    .withBucketName(bucketName).withKey(key)
                    .withUploadId(uploadId).withPartNumber(1)
                    .withInputStream(is)
                    .withObjectMetadata(metadata)
                    .withPartSize(size);

UploadPartResult uploadPartResult1 = s3.uploadPart(uploadRequest1);
            PartETag partETag1 = uploadPartResult1.getPartETag();

UploadPartRequest uploadRequest2 = new UploadPartRequest()
                    .withBucketName(bucketName).withKey(key)
                    .withUploadId(uploadId).withPartNumber(2)
                    .withInputStream(is)
                    .withObjectMetadata(metadata);

UploadPartResult uploadPartResult2 = s3.uploadPart(uploadRequest2);
            PartETag partETag2 = uploadPartResult2.getPartETag();

List<PartETag> partETagList = new ArrayList<PartETag>();
            partETagList.add(new PartETag(1, partETag1.getETag()));
            partETagList.add(new PartETag(2, partETag2.getETag()));

CompleteMultipartUploadRequest completeRequest = new
                    CompleteMultipartUploadRequest(
                    bucketName,
                    key,
                    uploadId,
                    partETagList);
            s3.completeMultipartUpload(completeRequest);
```

**Comment by andrewgaul** [comment]
The first symptom seems straightforward; S3Proxy does not support for pagination while [listing uploaded parts](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html).  The AWS SDK seems to unconditionally pass `part-number-marker` even though the initial call need not specify this.  Could you implement support for this case?

I cannot replicate the second symptom either due to me incorrectly transliterating the test or the flaky Internet where I am traveling.  Can you open a separate issue for this symptom and create a pull request with the exact failing test case?  Also please include the debug logs from this test.

**Comment by andrewgaul** [comment]
I cannot reproduce your symptoms.  Can you provide a test similar to the above which does exhibit them?

**Comment by ritazh** [comment]
Sorry for the delay on this. In a hackathon this week, will come back to this in a few days.

**Comment by ritazh** [comment]
Confirming based on the client-side implementation in d5822bf, this issue is resolved. Here is the updated code for reference:

```
TransferManager tm = new TransferManager(s3);   
ObjectMetadata metadata = new ObjectMetadata();
metadata.setContentType("application/unknown");
File file = new File(filePath);
InputStream is = new FileInputStream(filePath);
metadata.setContentLength(file.length());
// Ensure to call this particular method with metadata
Upload upload = tm.upload(bucketName, keylarge, is, metadata);
```
